"""
utils.py — Utility functions for ActiveWiki.
Logging, stats, export, and helper functions.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

logger = logging.getLogger("activewiki")


def setup_logging(level: str = "INFO"):
    """Configure ActiveWiki logging."""
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s [ActiveWiki] %(message)s",
        datefmt="%H:%M:%S",
    )


def export_report(wiki_status: dict, hypotheses: list, results: list, output_path: str = "report.md") -> str:
    """Export a human-readable Markdown report of the last loop."""
    now = datetime.now(timezone.utc).strftime("%d %B %Y %H:%M UTC")
    md = f"# ActiveWiki Report — {now}\n\n"

    # Status
    md += "## Status\n\n"
    for key, value in wiki_status.items():
        md += f"- **{key}**: {value}\n"

    # Hypotheses
    md += f"\n## Hypotheses Generated ({len(hypotheses)})\n\n"
    for h in hypotheses:
        conf = h.get("confidence", 0)
        md += f"- [{conf:.0%}] **{h.get('type', '?')}**: {h.get('hypothesis', '?')[:100]}\n"

    # Results
    if results:
        md += f"\n## Results ({len(results)})\n\n"
        successes = sum(1 for r in results if r.get("success"))
        md += f"- ✓ Confirmed: {successes}\n"
        md += f"- ✗ Failed: {len(results) - successes}\n"

    md += f"\n---\n*Generated by [ActiveWiki](https://github.com/drakkB/activewiki)*\n"

    Path(output_path).write_text(md)
    return md


def calculate_loop_stats(lessons: list) -> dict:
    """Calculate statistics about the current knowledge state."""
    if not lessons:
        return {"total": 0, "avg_strength": 0, "strong": 0, "weak": 0, "high_conf": 0}

    strengths = [l.get("strength", 1.0) for l in lessons]
    return {
        "total": len(lessons),
        "avg_strength": round(sum(strengths) / len(strengths), 3),
        "strong": sum(1 for s in strengths if s >= 0.7),
        "weak": sum(1 for s in strengths if s < 0.4),
        "high_confidence": sum(1 for l in lessons if l.get("confidence") == "high"),
        "types": list(set(l.get("type", "general") for l in lessons)),
    }


def merge_wikis(wiki_a_dir: str, wiki_b_dir: str, output_dir: str) -> dict:
    """Merge two ActiveWiki instances into one (for collaboration)."""
    a_dir = Path(wiki_a_dir)
    b_dir = Path(wiki_b_dir)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    merged_lessons = []
    merged_count = 0

    # Load lessons from both
    for d in [a_dir, b_dir]:
        lessons_file = d / "lessons.json"
        if lessons_file.exists():
            try:
                lessons = json.loads(lessons_file.read_text())
                merged_lessons.extend(lessons)
                merged_count += len(lessons)
            except:
                pass

    # Deduplicate by finding
    seen = set()
    unique = []
    for l in merged_lessons:
        key = l.get("finding", "")[:50]
        if key not in seen:
            seen.add(key)
            unique.append(l)

    # Save merged
    (out_dir / "lessons.json").write_text(json.dumps(unique, indent=2, default=str))

    # Copy wiki pages from both
    wiki_out = out_dir / "wiki"
    wiki_out.mkdir(exist_ok=True)
    for d in [a_dir, b_dir]:
        wiki_d = d / "wiki"
        if wiki_d.exists():
            for f in wiki_d.glob("*.md"):
                target = wiki_out / f.name
                if not target.exists():
                    target.write_text(f.read_text())

    return {
        "total_lessons_input": merged_count,
        "unique_lessons": len(unique),
        "duplicates_removed": merged_count - len(unique),
    }
